
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract MultiplicationContract {

    uint public TotalMult = 1;

    constructor() public {
        // Check that contract's public key is set
        require(tvm.pubkey() != 0, 101);
        // Check that message has signature (msg.pubkey() is not zero) and
        // message is signed with the owner's private key
        require(msg.pubkey() == tvm.pubkey(), 102);
        
        tvm.accept();
    }

    function Multiply(uint a) external {
        
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();

        require(a >= 1 && a <= 10 , 101, "Only 1-10 numbers can be used");
        TotalMult *= a;
    }
}
